### ISSUE TITLE
Using external 3rd party APIs 

### ISSUE THREAD

**Issue by adamjw3** [mandiwise/basic-apollo-federation-demo#5]
Hi

What if you didn’t have the data locally but it was coming from a 3rd party api or multiple APIs? 

E.g shopify graphql, contentful graphql, some rest api. 

Any examples?

**Comment by mandiwise** [comment]
At the moment I think your best bet is to wrap it in an Apollo `DataSource`, which I understand wouldn't be ideal if you're trying to incorporate the entire third party API into your graph, rather than a small subset of it.

There are some interesting things on the horizon with Apollo Federation that may address this in the future though. I'd recommend watching this talk from this year's GraphQL Summit: https://www.youtube.com/watch?v=MvHzOwdLb_o&list=PLpi1lPB6opQxkOv1H0j4JHhHx9bydEk8H&index=8
